version: '3.7'
services:
  application:
    image: m400/jupyterlab
    environment:               #comment out to enable https
    - CERT=                    #comment out to enable https
    ports:
    - 8888:8888
    volumes:
    - notebooks1:/notebooks
    - config:/root/.jupyter
    - pkgs1:/root/miniconda3/pkg
    - lib1:/root/miniconda3/lib

    restart: unless-stopped
volumes:
  notebooks1:
  config:
  pkgs1:
  lib1:

